stages:
  - test
  - build
  - deploy

variables:
  AWS_ECR_REPOSITORY: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

default:
  tags:
    - docker

test:
  stage: test
  before_script: 
    - echo "Prepare test data..."
  script:
    - echo "Run tests..."
  after_script:
    - echo "Clean..."

test run script:
  stage: test
  script:
    - ./ test.sh
  needs:
    - test

.config:
  before_script:
    - echo "Docker login with $AWS_ECR_REPOSITORY..."
    - echo "Setup ssh setting for docker context..."    

build:
  stage: build
  extends: .config
  script:
    - echo "Build docker image..."
  after_script:
    - echo "Push to ECR..." 

deploy dev:
  stage: deploy
  extends: .config
  script:
    - echo "Deploy docker in dev..."

deploy test:
  stage: deploy
  extends: .config
  script:
    - echo "Deploy docker in test..."

deploy prod:
  stage: deploy
  extends: .config
  script:
    - echo "Deploy docker in prod..."